sort:
  direction: desc
  by: filename

nav:
    - 主页: index.md
    - 技术: tech
    - 专栏: topic
    - 博客: blog
    - 语雀: yuque
    - 摘录: article
    - 留言: message
    - 关于: readme
    - 友链: flinks
    - RSS: rss.xml
